name: build fonts
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Run Git LFS
      #   run: git lfs install
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Configure PNPM settings
        run: |
          pnpm config set progress false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-


      - name: Install dependencies
        run: pnpm install


      - name: Install ttfautohint
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ttfautohint

      - name: Build Font
        run: pnpm run --silent build -- ttf::${{ matrix.font-name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.font-name }}"
          path: "dist/${{ matrix.font-name }}"
          if-no-files-found: error
          retention-days: 90

    strategy:
      # max-parallel: 1
      matrix:
        font-name: ["lj-iosevka-term", "lj-iosevka-fcmono", "lj-iosevka-aile", "lj-iosevka-etoile"]

