name: build fonts
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Run Git LFS
      #   run: git lfs install
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: latest

      - name: Configure PNPM settings
        shell: sh
        run: |
          pnpm config set progress false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: sh
        run: |
          pnpm store path
          echo "STORE_PATH=$(pnpm store path | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Cache rotation keys
        id: cache-rotation
        shell: sh
        run: |
          echo "YEAR_MONTH=$(date -u "+%Y%m")" >> $GITHUB_OUTPUT
          echo "YEAR_WEEK=$(date -u "+%Y%W")" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-

      - name: Install dependencies
        shell: sh
        run: pnpm install --prefer-offline


      - name: Install ttfautohint
        shell: sh
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ttfautohint

      - name: Build Font
        shell: sh
        run: pnpm run --silent build -- ttf::${{ matrix.font-name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.font-name }}"
          path: "dist/${{ matrix.font-name }}"
          if-no-files-found: error
          retention-days: 90

    strategy:
      # max-parallel: 1
      matrix:
        font-name: ["lj-iosevka-term", "lj-iosevka-fcmono", "lj-iosevka-aile", "lj-iosevka-etoile"]

